### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by ghost** [ATFinke-Productions/Steppy-2#3]
I have a problem

![zrzut ekranu 2015-04-21 o 19 51 37](https://cloud.githubusercontent.com/assets/6787484/7258913/e2c9377a-e85f-11e4-9f5f-7fd15c076183.png)

**Comment by atfinke** [comment]
The current version of Steppy 2 was built with Xcode 6.2, Swift version 1.2. Please ensure that you are using that version of Xcode.

**Comment by ghost** [comment]
Are you planning updates?

**Comment by atfinke** [comment]
Yes. It has now been updated.
