### ISSUE TITLE
Refresh from Apple Health total combined steps?

### ISSUE THREAD

**Issue by osimons** [ATFinke-Productions/Steppy-2#6]
In Apple Health I have two sources for steps – the iPhone + a Basis Peak activity tracker watch. Steppy 2 will not update the combined Health step total until after I've opened Health app forcing it to update the new totals. Can Steppy 2 periodically poll Health and force it to update, or is there no such API available? If possible it should at least make this call whenever refreshing the Today widget and App display to get latest numbers.

**Comment by osimons** [comment]
For the "Today" widget to show correct data, I must now first open Health app for Health to refresh combined steps, and then open Steppy 2 app for it to read latest data from Health. Then at least the data will be correct in widget also – at least until I move again ;-)

**Comment by atfinke** [comment]
From what I have seen, HealthKit only publishes new data periodically, or when the Health app is opened. This means that if I fetch new data once and then again 10 minutes later, the data Steppy receives is the same even if you have taken more steps.
